config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :items

  get 'signup', to: 'users#new'

  post 'users', to: 'users#create'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'userorder/:id', to: 'users#userorder', :as => :userorder

  resources :categories
  
  resources :carts

  resources :orderitems

  resources :orders

  resources :charges

end

app/models/user.rb
# model User
class User < ActiveRecord::Base
  has_many :items, dependent: :destroy
  has_many :orders
  # before_save { self.email = email.downcase }

  validates :username, presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 50 }
  # check code by stack over-flow
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  validates :email, presence: true,
            uniqueness: { case_sensitive: false },
            length: { mininum: 10, maximum: 100 },
            format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  # upload image

  mount_uploader :avatar, AvatarUploader

  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  after_update :crop_avatar

  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end
end

app/controllers/users_controller.rb
# UsersController
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]

  before_action :require_user, only: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  before_action :require_admin, only: [:destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      if params[:user][:avatar].present?
        render :crop
      else
        flash[:success] = 'Welcome to Goldenshop'
        redirect_to root_path
      end
    else
      render 'new'
    end
  end

  def edit; end

  def userorder
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      if params[:user][:avatar].present?
        render :crop
      else
        flash[:success] = 'Your account has successfully edited'
        redirect_to items_path
      end
    else
      render 'edit'
    end
  end

  def show
    @user_items = @user.items.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = 'User and all items created by user have been deleted'
    if !current_user.admin?
      session[:user_id] = nil
    end
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :avatar)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if (current_user != @user) && !current_user.admin?
      flash[:danger] = 'You can only edit your own account'
      redirect_to root_path
    end
  end

  def require_admin
    return unless logged_in? && !current_user.admin?
    flash[:danger] = 'Only Admin can perform that action'
    redirect_to root_path
  end
end

app/views/users/_form.html.erb
<%= render 'shared/errors_user'%>

<!-- Create Form -->
<div class="row">
	<div class="col-xs-12">
		<!-- Create Form -->		
		<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<!-- Title -->
			<div class="form-group">

				<div class="control-label col-sm-2">		
					<%= f.label :username %>
				</div>

				<div class="col-sm-8">	
					<%= f.text_field :username, class: "form-control", placeholder: "Enter your username", autofocus: true %>
				</div>	

			</div>
			<!-- Description -->
			<div class="form-group">

				<div class="control-label col-sm-2">
					<%= f.label :email %>
				</div>

				<div class="col-sm-8">
					<%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
				</div>

			</div>

			<!-- Password -->
			<div class="form-group">

				<div class="control-label col-sm-2">
					<%= f.label :password %>
				</div>

				<div class="col-sm-8">
					<%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
				</div>

			</div>
			<!-- Upload avatar -->
			<% if logged_in? %>
			<div class="form-group">

				<div class="control-label col-sm-2">
					<%= f.label :avatar %>
				</div>
			
				<div class="col-sm-8">
					<%= f.file_field :avatar, class: "form-control", placeholder: "Your avatar imgage..." %>
				</div>
			
			</div>
			<% end %>
			
			<!-- Submit btn -->
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: "btn btn-primary btn-lg")%>
				</div>		
			</div>
	</div>
</div>

				
		<% end %>
		<div class="col-xs-4 col-sm-offset-4">					
			<%= link_to 'Cancel request and return to item listing', items_path%>
		</div>

	</div>
</div>

app/views/users/crop.html.erb
<h1>Crop Avatar</h1>
<%= image_tag @user.avatar_url(:large), id: "cropbox" %>
<h4>Preview</h4>
<div style="width:100px; height:100px; overflow:hidden">
  <%= image_tag @user.avatar.url, :id => "preview" %>
</div>
<%= form_for @user do |f| %>
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>
  <div class="actions">
    <%= f.submit "Crop" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="custom_h1">Edit your account</h1>


<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="custom_h1">All Goldenshop User</h1>
<div align="center">

	<%= will_paginate %>
	
	<% @users.each do |user| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
					<li><% if user.avatar? %>
							<%= image_tag user.avatar.url(:thumb) %>
						<% else %>
							<%= link_to gravatar_for(user), user_path(user) %>
						<% end %>
					</li>
					<li class="article-title">
						<%= link_to user.username, user_path(user)%>
					</li>
					<li><small><%= pluralize(user.items.count, "item") if user.items %></small></li>
					<% if logged_in? and current_user.admin?%>
						<li><%= link_to "Delete this user", user_path(user), class: "btn btn-danger",
						method: :delete,
					data: { confirm: "Are you sure?" } %></li>
					<% end %>
				</div>
			</div>
		</ul>		
	<% end %>

	<%= will_paginate %>
	
</div>

app/views/users/new.html.erb
<h1 class="custom_h1">Sign up for Goldenshop</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="custom_h1"> Welcome to <%= @user.username %>'s page </h1>

<div class="row">
	<div class="container">
		<div align="center">
			<%= image_tag @user.avatar.url(:thumb) if @user.avatar? %>
		</div>
	</div>
</div>

<h4 class="custom_h1"><%= @user.username %>'s items</h4>

<%= render 'items/item', obj: @user.items %>

app/views/users/userorder.html.erb
<h1 class="custom_h1"> Welcome to <%= @user.username %>'s page </h1>

<div class="row">
	<div class="container">
		<div align="center">
			<%= image_tag @user.avatar.url(:thumb) if @user.avatar? %>
		</div>
	</div>
</div>

<h4 class="custom_h1"><%= @user.username %>'s orders</h4>

<table class="table table-striped">
	<tr class="active">
		<th>Created At</th>
		<th>Total price</th>
		<th>Status</th>
	</tr>
	<% @user.orders.each do |order| %>
	<tr>
		<td><%= link_to order.created_at, order_path(order) %></td> 
		<td><strong style="color: green">$</strong><%= order.total_price %></td> 

		<td>
			<%= form_for(:order, :url => order_path(order),method: :put, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      			<%= f.select :status, options_for_select(["New","Preparing","Shipping","Done","Cancel refund"], order.status)%>
      			<% if current_user.admin %>
      				<%= f.submit "Update status", class: "btn-sm btn-primary btn"  %>
    			<% end %>
    		<% end%>   	
   		</td> 
 	</tr>
 	<% end%>

</table>