config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :items

  get 'signup', to: 'users#new'

  post 'users', to: 'users#create'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'userorder/:id', to: 'users#userorder', :as => :userorder

  resources :categories
  
  resources :carts

  resources :orderitems

  resources :orders

  resources :charges

end

app/models/order.rb
# Order
class Order < ActiveRecord::Base
  has_many :order_items, dependent: :destroy
  belongs_to :user
end

app/controllers/orders_controller.rb
# OrdersController
class OrdersController < ApplicationController
  before_action :require_user, only: [:show]

  before_action :require_admin, only: [:destroy, :edit, :update]

  def index
    @orders = Order.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @order = Order.find(params[:id])
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user
    if @order.save
      Cart.find(session[:cart_id]).order_items.each do |item|
        item.order = @order
        item.save
      end
      # create new cart
      Cart.find(session[:cart_id]).destroy
      @cart = Cart.new
      @cart.save
      session[:cart_id] = @cart.id
      #
      flash[:success] = 'Your Order was successfully created'
      redirect_to order_path(@order)
    else
      render 'new'
    end
  end

  def update
    @order = Order.find(params[:id])

    if @order.update(order_params)

      flash[:success] = 'Order was succesfully updated'
      redirect_to order_path(@order)
    else
      render 'edit'
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  private

  def order_params
    params.require(:order).permit(:status, :total_price)
  end

  def require_admin
    return unless logged_in? && !current_user.admin?
    flash[:danger] = 'Only Admin can perform that action'
    redirect_to root_path
  end
end

app/views/orders/edit.html.erb
<h1 class="custom_h1">Your Order</h1>

<div align="center">
    <%= form_for(:order, :url => order_path(@order),method: :put, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <%= f.select :status, options_for_select(["New","Done"], @order.status) %>
      <%= f.submit "Update status", class: "btn btn-primary"  %>
    <% end%>
</div>
</br>

<table class="table table-striped">
  <tr class="active">
    <th>Item</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  <% @order.order_items.each do |item| %>
  <tr>
    <td><%= item.order_item_title %></td> 
    <td><%= item.quantity_order %></td> 
    <td><%= item.order_item_price %></td>   
  </tr>
  <% end%>

  <td></td>
  <td></td>
  <td><strong>$</strong><%= @order.total_price %></td>
</table>

app/views/orders/index.html.erb
<h1 class="custom_h1">All Order</h1>
<table class="table table-striped">
  <tr class="active">
    <th>Created At</th>
    <th>Customer</th>
    <th>Email</th>
    <th>Total price</th>
    <th>Status</th>
  </tr>
  <% Order.all.each do |order| %>
    <tr>
      <td><%= link_to order.created_at, order_path(order) %></td> 
      <td><%= link_to order.user.username, user_path(order.user) %></td>
      <td><%= order.user.email %></td>
      <td><strong style="color: green">$</strong><%= order.total_price %></td>     
      
      <td>   
              <%= form_for(:order, :url => order_path(order),method: :put, :html => {class: "form-horizontal", role: "form"}) do |f| %>
              <%= f.select :status, options_for_select(["New","Preparing","Shipping","Done","Cancel refund"], order.status)%>
              <% if current_user.admin %>
                <%= f.submit "Update status", class: "btn-sm btn-primary btn"  %>
              <% end %>
          <% end%>   
      </td> 
    </tr>
  <% end%>
</table>

app/views/orders/show.html.erb
<h1 class="custom_h1"><%= link_to @order.user.username, user_path(@order.user)%>'s Order</h1>
<div align="center"><button class="btn-lg btn btn-primary"><%= @order.status %></button></div>
</br>
<table class="table table-striped">
  <tr class="active">
    <th>Item</th>
    <th>Quantity</th>
    <th>Price</th>
  </tr>
  <% @order.order_items.each do |item| %>
  <tr>
    <td><%= item.order_item_title %></td> 
    <td><%= item.quantity_order %></td> 
    <td><%= item.order_item_price %></td>   
  </tr>
  <% end%>

  <td></td>
  <td></td>
  <td><strong>$</strong><%= @order.total_price %></td>
</table>
<% if @order.status == "New"%>
    <%= form_tag charges_path, id:'chargeForm' do %>

                        <% if flash[:error].present? %>
                          <div id="error_explanation">
                            <p><%= flash[:error] %></p>
                          </div>
                        <% end %>

                      <script src="https://checkout.stripe.com/checkout.js"></script>
                      <%= hidden_field_tag 'stripeToken' %>
                      <%= hidden_field_tag 'amount', @order.total_price %>
                      <%= hidden_field_tag 'stripeEmail' %>
                      <%= hidden_field_tag 'order_id', @order.id %>
                      <button id="btn-buy" type="button" class="btn btn-success btn-lg"><span class="glyphicon glyphicon-ok"></span>Buy this!</button>
    <script>
        var handler = StripeCheckout.configure({
          key: '<%= Rails.configuration.stripe[:publishable_key] %>',
          token: function(token, arg) {
            document.getElementById("stripeToken").value = token.id;
            document.getElementById("stripeEmail").value = token.email;
            document.getElementById("chargeForm").submit();
          }
    });
    document.getElementById('btn-buy').addEventListener('click', function(e) {
          handler.open({
            name: 'Learn Rails',
            description: '<%= "Khoa" %> ($<%= @order.total_price %>)',
            amount: document.getElementById("amount").value * 100
        });
        e.preventDefault();
       })
    </script>
    <% end %>
<% end %>