config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :items

  get 'signup', to: 'users#new'

  post 'users', to: 'users#create'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'userorder/:id', to: 'users#userorder', :as => :userorder

  resources :categories
  
  resources :carts

  resources :orderitems

  resources :orders

  resources :charges

end

app/models/item.rb
# Item
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :item_categories
  has_many :categories, through: :item_categories
  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
  validates :price, presence: true
  validates :quantity_stock, presence: true
  validates :user_id, presence: true

  mount_uploader :image, ImageUploader

  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    else
      where('title LIKE ?', "%#{search}%")
    end
  end
end

app/controllers/items_controller.rb
# IemsController
class ItemsController < ApplicationController
  before_action :set_item, only: [:edit, :update, :show, :destroy]

  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @items = Item.search(params[:search]).paginate(page: params[:page], per_page: 5)
    @search = params[:search]
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      flash[:success] = 'Item was succesfully created'
      redirect_to item_path(@item)
    else
      render 'new'
    end
  end

  def update
    if @item.update(item_params)
      flash[:success] = 'item was succesfully updated'
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy

    flash[:danger] = 'Item was succesfully deleted'

    redirect_to items_path
  end

  private

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :quantity_stock, :image, category_ids: [])
  end

  def require_same_user
    return if (current_user != @item.user) || !current_user.admin?
    flash[:danger] = 'You can only edit or delete your own items'
    redirect_to root_path
  end
end

app/views/items/_form.html.erb
 	<!-- Error message -->
<%= render 'shared/errors', obj: @item %>
<!-- Create Form -->
<div class="row">
	<div class="col-xs-12">
		<!-- Create Form -->		
		<%= form_for(@item, :html => {class: "form-horizontal", role: "form"}) do |f| %>
			<!-- Title -->
			<div class="form-group">

				<div class="control-label col-sm-2">		
					<%= f.label :title %>
				</div>

				<div class="col-sm-8">	
					<%= f.text_field :title, class: "form-control", placeholder: "Title of item", autofocus: true %>
				</div>	

			</div>
			<!-- Description input -->
			<div class="form-group">

				<div class="control-label col-sm-2">
					<%= f.label :description %>
				</div>

				<div class="col-sm-8">
					<%= f.text_area :description, class: "form-control", placeholder: "Body of item" %>
				</div>

			</div>
			<!-- Price input -->
			<div class="form-group">

				<div class="control-label col-sm-2">
					<%= f.label :price %>
				</div>

				<div class="col-sm-8">
					<%= f.text_area :price, class: "form-control", placeholder: "Price of item" %>
				</div>

			</div>
			<!-- Quantity in stock input -->
			<div class="form-group">

				<div class="control-label col-sm-2">
					<%= f.label :quantity_stock %>
				</div>

				<div class="col-sm-8">
					<%= f.text_area :quantity_stock, class: "form-control", placeholder: "Quantity of item" %>
				</div>

			</div>
			<!-- Categories Checkbox -->
			<div class="form-group">

				<div class="row">

					<div class="col-sm-offset-2 col-sm-8">

						<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
							<%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>

						<% end %>
						
					</div>

				</div>

			</div>
			<!-- Image -->
			<% if logged_in? %>
				<div class="form-group">

					<div class="control-label col-sm-2">
						<%= f.label :image %>
					</div>
				
					<div class="col-sm-8">
						<%= f.file_field :image, class: "form-control", placeholder: "Your item imgage..." %>
					</div>
				
				</div>
			<% end %>
			<!-- Submit btn -->
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<%= f.submit class: "btn btn-primary btn-lg" %>
				</div>		
			</div>
	</div>
</div>

				
		<% end %>
		<div class="col-xs-4 col-sm-offset-4">					
			<%= link_to 'Cancel request and return to items listing', items_path%>
		</div>

	</div>
</div>

app/views/items/_item.html.erb
	<% obj.each do |item| %>
		<div class="row">
			<div class="col-xs-8 col-xs-offset-2">
				<div class="well well-lg">
					<div class="article-titles">
						<%= link_to item.title, item_path(item) %>	
					</div>
					<div class="article-body">
						<div align="left">
							<%= image_tag item.image.url, style:"height: 300px ; width: 200px;" if item.image? %>
						</div>
					</div>
					<div class="article-body"> 						
						<%=  truncate(item.description, length: 100) %>
					</div>
					<div class="article-body"> 						
						$<%=  link_to item.price.round(2), item_path(item) %>
					</div>	
					<div class="article-body"> 						
						<%=  link_to item.quantity_stock, item_path(item) %>
					</div>	
					
					<div class="article-meta-details">
						<small> <strong>Create by : </strong><%= link_to(item.user.username , user_path(item.user))if item.user %>,
							<%= time_ago_in_words(item.created_at)%> ago,
							<strong>Last updated : </strong> <%= time_ago_in_words(item.updated_at) %> ago.
						</small>
					</div>
					
					<% if item.categories.any? %>
						<p><strong>Categories : </strong><%= render item.categories %></p>
					<% end %>

					<div class="item-actions">
						<% if logged_in? && (current_user == item.user || current_user.admin?) %>
							<%= link_to 'Edit this item', edit_item_path(item), class: "btn btn-xs btn-primary" %>
							<%= link_to "Delete this item", item_path(item), method: :delete, 
																	data: {confirm: "Are you sure?"}, 
																	class: "btn btn-xs btn-danger" %>
							<% end %>										
						<%= link_to 'Back to Item Listing', items_path, class: "btn btn-xs btn-success" %>

					</div>					
				</div>
			</div>
		</div>

	<% end %>

</table>

app/views/items/edit.html.erb
<h1 class="custom_h1">Edit existing article</h1>

<%=render 'form' %>

app/views/items/index.html.erb
	<% if @search == "" %>
		<h1 class="custom_h1">All Item</h1>
	<% else %>
		<h1 class="custom_h1">All results for "<%= @search %>"</h1>
	<% end %>
<div align="center">
	<%= will_paginate %>
</div>

<%= render 'item', obj: @items %>

<div align="center">
	<%= will_paginate %>
</div>	

app/views/items/new.html.erb
<h1 class="custom_h1">Create an Item</h1>

<%=render 'form' %> 	

app/views/items/show.html.erb
<h2 class="custom_h1">Title: <%= @item.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">	
<% if @item.user %>
	<ul class="listing">
		<div align="center" class="none-border">
			<div class="row">
				<div class="col-md-4 col-md-offset-4">
					<li><%= link_to gravatar_for(@item.user), user_path(@item.user) %></li>
					<li class="article-title">
						<%= link_to @item.user.username, user_path(@item.user)%>
					</li>
					<li><small><%= pluralize(@item.user.items.count, "item") if @item.user.items %></small></li>
				</div>
			</div>
		</div>	
	</ul>	
<% end %>

	<h4 class="center description"><strong>Description:</strong></h4>
		<div class="article-body">
			<div align="center">
				<%= image_tag @item.image.url, style:"height: 300px ; width: 200px;" if @item.image? %>
			</div>
		</div>
		<div class="article-body"> 						
			<%=  truncate(@item.description, length: 100) %>
		</div>
		<div class="article-body"> 						
			$<%=  link_to @item.price.round(2), item_path(@item) %>
		</div>	
		<div class="article-body"> 						
			<%=  link_to @item.quantity_stock, item_path(@item) %>
		</div>	
	<!-- tag -->
	<% if @item.categories.any? %>
		<p><strong>Categories: </strong><%= render @item.categories %></p>
	<% end %>
	<!-- tag -->
	<div class="item-actions">
		<% if logged_in? && (current_user == @item.user || current_user.admin?) %>
			<%= link_to 'Edit this item', edit_item_path(@item), class: "btn btn-xs btn-primary" %>
			<%= link_to "Delete this item", item_path(@item), method: :delete, 
													data: {confirm: "Are you sure?"}, 
													class: "btn btn-xs btn-danger" %>

		<% end %>	
		
		<%= link_to 'Back to Item Listing', items_path, class: "btn btn-xs btn-success" %>
		
		<%= form_for(:order_item, :url => orderitems_path,:html => {class: "form-horizontal", role: "form"}) do |f| %>
			<%= f.hidden_field :order_item_title, value: @item.title, class: "form-control" %> 
			<%= f.label :quantity_order %>
			<%= f.text_area :quantity_order, value: 1, class: "form-control", placeholder: "Quantity of item" %>
			<%= f.hidden_field :order_item_price, value: @item.price, class: "form-control", placeholder: "Price of item" %>
			<%= f.submit class: "btn btn-primary btn-lg" %>
		<% end%>

	</div>
</div>