config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#home'
  get 'about', to: 'welcome#about'

  resources :items

  get 'signup', to: 'users#new'

  post 'users', to: 'users#create'

  resources :users, except: [:new]

  get 'login', to: 'sessions#new'

  post 'login', to: 'sessions#create'

  delete 'logout', to: 'sessions#destroy'

  get 'userorder/:id', to: 'users#userorder', :as => :userorder

  resources :categories
  
  resources :carts

  resources :orderitems

  resources :orders

  resources :charges

end

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
			Copyright &copy; <a href="https://github.com/thaivankhoa/first_rails">The First Rails Application</a>
			by <a href="https://www.fb.com/tvkhyoa">Khoa Thai</a>
		</small>

		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
			</ul>
		</nav>
	</footer>
</div>

app/views/layouts/_message.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
			<div class='alert alert-<%="#{name}" %>'>
				<a href="#" class="close" data-dismiss="alert">&#215;</a>
				<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
			</div>	
		<% end %>	
	</div>
</div>	

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Golden Shop", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Menu -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
       <li><%= link_to "Items", items_path %></li>
      <% if logged_in? %>  
        
        

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All users", users_path %></li>
            <li><%= link_to "Sell an item", new_item_path %></li>
            <li><%= link_to "Your Orders" + " (#{current_user.orders.count})", userorder_path(current_user) %></li>
            <!--
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
            -->
          </ul>
        </li>
       <% end %> 
      
        <!-- Category -->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <!-- <li><a href="#">Action</a></li> -->
            <li><%= link_to "All categories", categories_path %></li>
            <% Category.all.each do |category| %>
              <li><%= link_to "#{category.name}", category_path(category) %></li>
            <% end %>

            <% if logged_in? and current_user.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create New Category", new_category_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <!-- Check order for admin -->
      <% if logged_in? and current_user.admin? %>
        <ul class="nav navbar-nav">  
          <li><%= link_to "All Orders", orders_path %></li>
        </ul>
      <% end %>
      <!-- Search -->    
      <ul class="navbar-form navbar-left"> 
        <div>
              <%= form_tag items_path, :method => 'get' do %>
              <%= text_field_tag :search, params[:search] %>
              <%= submit_tag "Search", :name => nil %>
          <% end %>
        </div>
          </ul>
      <!-- -->
      <!-- Log in, log out -->
      <ul class="nav navbar-nav navbar-right">      
         <% if logged_in? %>
          <li class="active"><%= link_to "Your cart" + " (#{Cart.find(session[:cart_id]).order_items.count})", cart_path(Cart.find(session[:cart_id])) %></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit your profile", edit_user_path(session[:user_id]) %></li>
              <li><%= link_to "View your profile", user_path(session[:user_id]) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
            </ul>
          </li>
      <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Sign up", signup_path %></li>     
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoldenShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<%= render 'layouts/navigation' %>
  <%= render 'layouts/message' %>

	<div class="container">
    	<%= yield %>   
 	</div>  
  
     <%= render 'layouts/footer'%>
     
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>